### ISSUE TITLE
Failing tests due to certificate

### ISSUE THREAD

**Issue by edewit** [fabric8-launcher/launcher-application#781] opened 2019-06-12 08:31 UTC
### Description

Running the tests on the `creator_backend` branch fails, ran the tests with `./mvnw install`
```
$> java -version
openjdk version "1.8.0_212"
OpenJDK Runtime Environment (build 1.8.0_212-b04)
OpenJDK 64-Bit Server VM (build 25.212-b04, mixed mode)
$> hostnamectl   
   Static hostname: localhost.localdomain
         Icon name: computer-laptop
           Chassis: laptop
  Operating System: Fedora 30 (Workstation Edition)
       CPE OS Name: cpe:/o:fedoraproject:fedora:30
            Kernel: Linux 5.1.6-300.fc30.x86_64
      Architecture: x86-64
```
```
[ERROR] Errors: 
[ERROR]   BitbucketServiceTest>AbstractGitServiceTest.pushFile:279 » IllegalState An err...
[ERROR]   GitHubServiceTest>AbstractGitServiceTest.pushFile:279 » IllegalState An error ...
[ERROR]   GitLabServiceTest>AbstractGitServiceTest.pushFile:279 » IllegalState An error ...
```

### Error log

```
Caused by: sun.security.validator.ValidatorException: PKIX path validation failed: java.security.cert.CertPathValidatorException: Algorithm constraints check failed on keysize limits. RSA 1024bit key used with certificate: O=GoProxy untrusted MITM proxy Inc.  Usage was tls server
    at sun.security.validator.PKIXValidator.doValidate(PKIXValidator.java:362)
    at sun.security.validator.PKIXValidator.engineValidate(PKIXValidator.java:259)
    at sun.security.validator.Validator.validate(Validator.java:262)
    at sun.security.ssl.X509TrustManagerImpl.validate(X509TrustManagerImpl.java:324)
    at sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:229)
    at sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:105)
    at io.specto.hoverfly.junit.core.SslConfigurer$1.checkServerTrusted(SslConfigurer.java:123)
    at sun.security.ssl.AbstractTrustManagerWrapper.checkServerTrusted(SSLContextImpl.java:1091)
    at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1621)
    ... 81 more
Caused by: java.security.cert.CertPathValidatorException: Algorithm constraints check failed on keysize limits. RSA 1024bit key used with certificate: O=GoProxy untrusted MITM proxy Inc.  Usage was tls server
    at sun.security.provider.certpath.PKIXMasterCertPathValidator.validate(PKIXMasterCertPathValidator.java:135)
    at sun.security.provider.certpath.PKIXCertPathValidator.validate(PKIXCertPathValidator.java:233)
    at sun.security.provider.certpath.PKIXCertPathValidator.validate(PKIXCertPathValidator.java:141)
    at sun.security.provider.certpath.PKIXCertPathValidator.engineValidate(PKIXCertPathValidator.java:80)
    at java.security.cert.CertPathValidator.validate(CertPathValidator.java:292)
    at sun.security.validator.PKIXValidator.doValidate(PKIXValidator.java:357)
    ... 89 more
Caused by: java.security.cert.CertPathValidatorException: Algorithm constraints check failed on keysize limits. RSA 1024bit key used with certificate: O=GoProxy untrusted MITM proxy Inc.  Usage was tls server
    at sun.security.util.DisabledAlgorithmConstraints$KeySizeConstraint.permits(DisabledAlgorithmConstraints.java:817)
    at sun.security.util.DisabledAlgorithmConstraints$Constraints.permits(DisabledAlgorithmConstraints.java:419)
    at sun.security.util.DisabledAlgorithmConstraints.permits(DisabledAlgorithmConstraints.java:167)
    at sun.security.provider.certpath.AlgorithmChecker.check(AlgorithmChecker.java:326)
    at sun.security.provider.certpath.PKIXMasterCertPathValidator.validate(PKIXMasterCertPathValidator.java:125)
    ... 94 more
```

**Comment by quintesse** [comment] 2019-06-12 09:02
Might be environment-related because it works for me (and @gastaldi apparently) and my Java version is the same as @edewit 's. Fedora 30 perhaps?

**Comment by edewit** [comment] 2019-06-12 09:07
I think @gastaldi is also on Fedora 30

**Comment by gastaldi** [comment] 2019-08-17 02:24
Closing, reopen if the problem persists

**Closed by gastaldi** 2019-08-17 02:24 UTC

**Comment by jamezp** [comment] 2020-05-11 21:39
Was there a solution to this? I'm seeing the same issue on Fedora 31 and 32.

**Comment by gastaldi** [comment] 2020-05-11 21:52
@jamezp Nope, seems to be an environment issue, but I haven't been able to reproduce it

**Comment by jamezp** [comment] 2020-05-11 21:54
Do you use Java installed by DNF or do you download it from another source?

**Comment by gastaldi** [comment] 2020-05-11 21:55
I use SDKMan

**Comment by jamezp** [comment] 2020-05-11 21:58
Maybe it's the local policy configuration then. The defaults I have are:
```
jdk.certpath.disabledAlgorithms=MD2, MD5, SHA1 jdkCA & usage TLSServer, \
    RSA keySize < 1024, DSA keySize < 1024, EC keySize < 224
```
